services:
  db:
    image: postgres:alpine3.18
    container_name: "db_whiskey_notes"
    expose:
      - "5432"
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../db/database:/var/lib/postgresql/data
  djangoapp:
    image: django/djangoapp:1.0
    build: ./djangoapp
    container_name: "backend_whiskey_notes"
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ../djangoapp:/home/user1/dev
