# Generated by Django 4.2.18 on 2025-02-20 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, choices=[('SC', 'スコットランド'), ('IR', 'アイルランド'), ('AM', 'アメリカ'), ('CA', 'カナダ'), ('JA', '日本'), ('EX', 'その他')], max_length=2)),
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('cask', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiskey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
