# Generated by Django 4.2.20 on 2025-04-09 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastingnote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_whiskies', to=settings.AUTH_USER_MODEL),
        ),
    ]
