# Generated by Django 4.2.20 on 2025-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastingnote',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
